[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 18

[window]
padding = { x = 15, y = 15 }
